import type { CinemaSubagent, ModelTier } from './types';

export const SUBAGENTS: CinemaSubagent[] = [
  {
    key: 'SHOWRUNNER', name: 'Director Ejecutivo / Showrunner IA', role: 'Director + Productor ejecutivo',
    layer: 'Capa 0 – Orquestador General', layerId: 0,
    duties: ['Recibe el brief cinematográfico.', 'Define la biblia del proyecto.', 'Coordina a todos los subagentes.'],
    inputDescription: 'Sinopsis, presupuesto, género, duración, formato.',
    outputDescription: 'Project Bible unificado + Plan de producción estratégico.',
    suggestedPrompt: 'Genera el Project Bible para el proyecto indicado.',
    iconName: 'stars',
  },
  {
    key: 'GUIONISTA', name: 'Guionista Principal', role: 'Guionista de Cine',
    layer: 'Capa 1 – Narrativa', layerId: 1,
    duties: ['Genera sinopsis, tratamiento, escaleta y guion literario.', 'Escribe diálogos y acotaciones.'],
    inputDescription: 'Project Bible, notas del Showrunner, esquema de personajes.',
    outputDescription: 'Guion Literario con escenas y diálogos.',
    suggestedPrompt: 'Escribe el guion literario basado en la biblia del proyecto.',
    iconName: 'description',
  },
  {
    key: 'SCRIPT_DOCTOR', name: 'Script Doctor', role: 'Asesor y Pulidor de Guion',
    layer: 'Capa 1 – Narrativa', layerId: 1,
    duties: ['Mejora diálogos, ritmo y coherencia narrativa.', 'Ajusta el guion a restricciones de producción.'],
    inputDescription: 'Guion literario original, notas de revisión.',
    outputDescription: 'Guion Pulido con diálogos optimizados.',
    suggestedPrompt: 'Pule y mejora el guion existente.',
    iconName: 'healing',
  },
  {
    key: 'CONTINUISTA', name: 'Continuista', role: 'Script / Continuity Supervisor',
    layer: 'Capa 1 – Narrativa', layerId: 1,
    duties: ['Monitorea continuidad técnica y lógica.', 'Genera Continuity Bible.'],
    inputDescription: 'Guion literario pulido, esquemas de arte.',
    outputDescription: 'Continuity Bible detallada.',
    suggestedPrompt: 'Genera las especificaciones de continuidad del proyecto.',
    iconName: 'history',
  },
  {
    key: 'DIRECTOR_ESCENA', name: 'Director de Escena', role: 'Director Artístico / Bloqueador',
    layer: 'Capa 1 – Narrativa', layerId: 1,
    duties: ['Define intención emocional de cada escena.', 'Establece ritmo actoral y marcas de cámara.'],
    inputDescription: 'Guion literario, Continuity Bible.',
    outputDescription: 'Instrucciones de Intención Directorial.',
    suggestedPrompt: 'Genera el plan directorial para las escenas del proyecto.',
    iconName: 'movie',
  },
  {
    key: 'DIRECTOR_ARTE', name: 'Director de Arte', role: 'Concept & Environment Director',
    layer: 'Capa 2 – Visual', layerId: 2,
    duties: ['Define estética e identidad visual global.', 'Crea la Art Bible.'],
    inputDescription: 'Project Bible, Guion literario.',
    outputDescription: 'Art Bible con paleta de colores y estilos.',
    suggestedPrompt: 'Define la paleta cromática y estética del proyecto.',
    iconName: 'palette',
  },
  {
    key: 'CHARACTER_DESIGNER', name: 'Diseñador de Personajes', role: 'Diseñador Creativo de Personajes',
    layer: 'Capa 2 – Visual', layerId: 2,
    duties: ['Diseña personajes en turnaround.', 'Define proporciones, texturas y colores.'],
    inputDescription: 'Art Bible, descripciones de personajes.',
    outputDescription: 'Character Sheets y Turnaround referenciales.',
    suggestedPrompt: 'Genera fichas técnicas de personajes.',
    iconName: 'face',
  },
  {
    key: 'CHARACTER_SUPERVISOR', name: 'Supervisor de Personajes', role: 'Character Consistency Supervisor',
    layer: 'Capa 2 – Visual', layerId: 2,
    duties: ['Mantiene consistencia visual del personaje.', 'Emite tokens de consistencia.'],
    inputDescription: 'Character Sheets primarios, renders de prueba.',
    outputDescription: 'Guía de Coherencia Facial y Tokens.',
    suggestedPrompt: 'Escribe el instructivo técnico de consistencia de personajes.',
    iconName: 'portrait',
  },
  {
    key: 'PRODUCTION_DESIGNER', name: 'Diseñador de Producción', role: 'Production / Scenic Designer',
    layer: 'Capa 2 – Visual', layerId: 2,
    duties: ['Diseña entornos, arquitectura y props.', 'Crea blueprints de escenarios.'],
    inputDescription: 'Art Bible, descripciones escénicas.',
    outputDescription: 'Environment Blueprint y guías arquitectónicas.',
    suggestedPrompt: 'Diseña la arquitectura y ambientación del proyecto.',
    iconName: 'domain',
  },
  {
    key: 'DOP', name: 'Director de Fotografía', role: 'Director de Fotografía / DoP',
    layer: 'Capa 2 – Visual', layerId: 2,
    duties: ['Define lentes, composición y encuadres.', 'Diseña movimientos de cámara.'],
    inputDescription: 'Director\'s Plan, Environment Blueprints.',
    outputDescription: 'Camera & Lens Bible.',
    suggestedPrompt: 'Define la configuración de cámara del proyecto.',
    iconName: 'videocam',
  },
  {
    key: 'GAFFER', name: 'Gaffer / Iluminador', role: 'Chief Lighting Technician',
    layer: 'Capa 2 – Visual', layerId: 2,
    duties: ['Define esquemas de luz por escena.', 'Mantiene coherencia lumínica.'],
    inputDescription: 'Camera & Lens Bible, Art Bible.',
    outputDescription: 'Lighting Blueprint con temperaturas de color.',
    suggestedPrompt: 'Genera el esquema de iluminación del proyecto.',
    iconName: 'wb_sunny',
  },
  {
    key: 'STORYBOARD', name: 'Storyboarder', role: 'Storyboard Artist',
    layer: 'Capa 2 – Visual', layerId: 2,
    duties: ['Genera descripciones de planos y storyboard visual.', 'Define composición y transiciones.'],
    inputDescription: 'Director\'s Plan, Camera & Lens Bible.',
    outputDescription: 'Storyboard narrativo con descripciones de planos.',
    suggestedPrompt: 'Genera el storyboard narrativo completo del proyecto.',
    iconName: 'view_column',
  },
  {
    key: 'LEAD_ANIMATOR', name: 'Animador Líder', role: 'Lead Animator / Generador Video Principal',
    layer: 'Capa 3 – Animación y VFX', layerId: 3,
    duties: ['Genera los prompts maestros para video AI.', 'Define parámetros de movimiento.'],
    inputDescription: 'Storyboard, Character Sheets, Lighting Blueprint.',
    outputDescription: 'Prompts de Video AI optimizados.',
    suggestedPrompt: 'Genera prompts maestros para la animación del proyecto.',
    iconName: 'animation',
  },
  {
    key: 'SEC_ANIMATOR', name: 'Animador Secundario', role: '2nd Unit Animator',
    layer: 'Capa 3 – Animación y VFX', layerId: 3,
    duties: ['Genera planos complementarios.', 'Gestiona física de materiales.'],
    inputDescription: 'Prompts maestros del Animador Líder.',
    outputDescription: 'Prompts de Animación Secundaria.',
    suggestedPrompt: 'Genera prompts de animación para planos secundarios.',
    iconName: 'slow_motion_video',
  },
  {
    key: 'VFX_SUPERVISOR', name: 'Supervisor VFX', role: 'Visual Effects Supervisor',
    layer: 'Capa 3 – Animación y VFX', layerId: 3,
    duties: ['Diseña efectos visuales y partículas.', 'Supervisa composición digital.'],
    inputDescription: 'Planos animados, Art Bible.',
    outputDescription: 'VFX Blueprint y prompts de efectos especiales.',
    suggestedPrompt: 'Diseña los efectos visuales para el proyecto.',
    iconName: 'auto_fix_high',
  },
  {
    key: 'COMPOSER', name: 'Compositor Musical', role: 'Film Score Composer',
    layer: 'Capa 4 – Sonido', layerId: 4,
    duties: ['Crea la partitura musical del proyecto.', 'Define leitmotifs y temas.'],
    inputDescription: 'Director\'s Plan, Art Bible, guion.',
    outputDescription: 'Score completo con notación musical y prompts de síntesis.',
    suggestedPrompt: 'Compón la banda sonora del proyecto.',
    iconName: 'music_note',
  },
  {
    key: 'SOUND_DESIGNER', name: 'Diseñador de Sonido', role: 'Sound Designer',
    layer: 'Capa 4 – Sonido', layerId: 4,
    duties: ['Diseña efectos de sonido y foley.', 'Crea la atmósfera sonora.'],
    inputDescription: 'Storyboard, guion, Art Bible.',
    outputDescription: 'Sound Design Bible con efectos y prompts de síntesis.',
    suggestedPrompt: 'Diseña los efectos de sonido para el proyecto.',
    iconName: 'surround_sound',
  },
  {
    key: 'MIXER', name: 'Mezclador de Audio', role: 'Re-Recording Mixer',
    layer: 'Capa 4 – Sonido', layerId: 4,
    duties: ['Mezcla diálogos, música y efectos.', 'Define espacialización Atmos.'],
    inputDescription: 'Score, Sound Design Bible, guion.',
    outputDescription: 'Mix Blueprint con parámetros de mezcla final.',
    suggestedPrompt: 'Define los parámetros de mezcla de audio para el proyecto.',
    iconName: 'equalizer',
  },
  {
    key: 'EDITOR', name: 'Editor / Montajista', role: 'Film Editor',
    layer: 'Capa 5 – Postproducción', layerId: 5,
    duties: ['Define cortes, transiciones y ritmo de montaje.', 'Genera el EDL (Edit Decision List).'],
    inputDescription: 'Todos los planos animados, score, storyboard.',
    outputDescription: 'EDL y plan de montaje secuencial.',
    suggestedPrompt: 'Genera el plan de montaje y secuencia de edición del proyecto.',
    iconName: 'cut',
  },
  {
    key: 'COLORIST', name: 'Colorista', role: 'Digital Colorist / DI Supervisor',
    layer: 'Capa 5 – Postproducción', layerId: 5,
    duties: ['Realiza la corrección de color final.', 'Define el look cinematográfico de la película.'],
    inputDescription: 'Planos montados, Art Bible, Lighting Blueprint.',
    outputDescription: 'Color Grade Bible con LUTs y parámetros de corrección.',
    suggestedPrompt: 'Define la corrección de color y look visual del proyecto.',
    iconName: 'color_lens',
  },
  {
    key: 'VFX_COMPOSITOR', name: 'Compositor VFX', role: 'VFX Compositor / Finishing',
    layer: 'Capa 5 – Postproducción', layerId: 5,
    duties: ['Integra VFX en las imágenes finales.', 'Supervisa la composición de capas.'],
    inputDescription: 'Planos montados, VFX Blueprint.',
    outputDescription: 'Planos finales integrados y prompts de composición.',
    suggestedPrompt: 'Genera instrucciones de composición VFX final para el proyecto.',
    iconName: 'layers',
  },
  {
    key: 'VISUAL_QA', name: 'Supervisor de Calidad Visual IA', role: 'Visual QA Director (juez multimodal)',
    layer: 'Capa 5 – Postproducción', layerId: 5,
    duties: ['Audita los clips renderizados con un juez multimodal (Gemini, video input nativo).', 'Detecta parpadeos, mutaciones de extremidades y congelamientos.', 'Refina prompts y negativos acumulativos para los reintentos automáticos.'],
    inputDescription: 'Clips renderizados + prompts originales de las tomas.',
    outputDescription: 'Veredicto de aprobación (tri-estado) + refinamientos de prompt por toma.',
    suggestedPrompt: 'Audita la consistencia visual de los clips renderizados y propón refinamientos para las tomas defectuosas.',
    iconName: 'fact_check',
  },
  {
    key: 'PRODUCER', name: 'Productor de Línea', role: 'Line Producer',
    layer: 'Capa 6 – Producción y Control', layerId: 6,
    duties: ['Gestiona presupuesto y tiempos de producción.', 'Coordina entregas y assets.'],
    inputDescription: 'Todos los entregables del proyecto.',
    outputDescription: 'Plan de producción con cronograma y presupuesto.',
    suggestedPrompt: 'Genera el plan de producción y estimación de costos del proyecto.',
    iconName: 'account_balance',
  },
  {
    key: 'QA_SUPERVISOR', name: 'Supervisor de Calidad', role: 'QA / Deliverables Supervisor',
    layer: 'Capa 6 – Producción y Control', layerId: 6,
    duties: ['Verifica coherencia entre todos los entregables.', 'Emite reporte de calidad final.'],
    inputDescription: 'Todos los entregables del proyecto.',
    outputDescription: 'Reporte de QA con observaciones y aprobación final.',
    suggestedPrompt: 'Realiza el control de calidad completo del proyecto cinematográfico.',
    iconName: 'verified',
  },
  {
    key: 'MARKETING', name: 'Director de Marketing', role: 'Marketing & Distribution Director',
    layer: 'Capa 6 – Producción y Control', layerId: 6,
    duties: ['Crea la estrategia de distribución y marketing.', 'Genera materiales promocionales.'],
    inputDescription: 'Project Bible, guion, Art Bible.',
    outputDescription: 'Plan de Marketing y Kit de Prensa.',
    suggestedPrompt: 'Genera el plan de marketing y distribución del proyecto.',
    iconName: 'campaign',
  },
];

// ─── Enrutador multi-modelo (Plan multi-rol) ──────────────────────────────────
// Tier por defecto de cada subagente de texto. El rol 'orchestrator' define un
// modelo por tier; los agentes heredan el de su tier salvo override individual.
//   premium  → razonamiento largo / creatividad (Project Bible, guion)
//   standard → entregables medios (art bible, storyboards, sonido)
//   economy  → documentos estructurados (planes, reportes, marketing)
export const SUBAGENT_TIERS: Record<string, ModelTier> = {
  SHOWRUNNER: 'premium',
  GUIONISTA: 'premium',
  SCRIPT_DOCTOR: 'premium',
  PRODUCER: 'economy',
  QA_SUPERVISOR: 'economy',
  MARKETING: 'economy',
};

export function getSubagentTier(key: string): ModelTier {
  return SUBAGENT_TIERS[key] ?? 'standard';
}
